department <- c("sewing" , "finishing", "sewing", "finishing")
team <- c("8", "1", '11', '11')
no_of_workers	<- c(1:4)

test_data <- data.frame(department, team, no_of_workers)
test_data_two_columns_depart_and_worker <- data.frame(department, no_of_workers)
test_data_two_columns_depart_and_team <- data.frame(department, team)
test_data_two_columns_team_and_worker<- data.frame(team, no_of_workers)
test_data_one_column_depart <- data.frame(department)
test_data_one_column_team <- data.frame(team)
test_data_one_column_work <- data.frame(no_of_workers)